import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import data from "../data/products";
import Link from 'next/link'

const inter = Inter({ subsets: ["latin"] });

export default function Home(props) {
  const { products } = props;
  if (!products) {
    return null;
  }

  return (
    <>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ul>
          {products.map((product) => (
            <li key={product.id}>
              {" "}
              <Link href={`/${product.id}`}>{product.title}</Link>
            </li>
          ))}
        </ul>
      </main>
    </>
  );
}

export function getStaticProps() {
  return {
    props: {
      products: data,
    },
  };
}
